apiDebug: true
password: '1234'
timeout: 600000
libPath: ./server/lib
dataFilename: ./server/dapp/dapp.presets.yaml
deployFilename: ./server/config/192.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: 'http://192.168.99.100:9000'
    stratoUrl: 'http://192.168.99.100/strato-api'
    blocUrl: 'http://192.168.99.100/bloc/v2.1'
    searchUrl: 'http://192.168.99.100/cirrus'
