apiDebug: true
password: '1234'
timeout: 600000
libPath: ./server/lib
contractsPath: ./contracts/
dataFilename: ./server/dapp/dapp.presets.yaml
deployFilename: ./server/config/localhost.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: 'http://localhost:9000'
    stratoUrl: 'http://localhost/strato-api'
    blocUrl: 'http://localhost/bloc/v2.2'
    searchUrl: 'http://localhost/cirrus'
