apiDebug: true
password: '1234'
timeout: 600000
libPath: ./server/lib
contractsPath: ./contracts/
dataFilename: ./server/dapp/dapp.presets.yaml
deployFilename: ./server/config/generated.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: '<STRATO_URL_placeholder>:9000'
    stratoUrl: '<STRATO_URL_placeholder>/strato-api'
    blocUrl: '<STRATO_URL_placeholder>/bloc/v2.2'
    searchUrl: '<STRATO_URL_placeholder>/cirrus'
